# This is a basic workflow to help you get started with Actions

name: CI-team-client

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'app-main/client/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'app-main/client/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build_ui
        uses: docker/build-push-action@v2
        with:
          context: app-main/client
          push: true
          tags: jgsathe/team1_client:latest
      -
        name: Image digest (UI)
        run: echo ${{ steps.docker_build_ui.outputs.digest }}
